In [50]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt

In [51]:
df = pd.read_csv('train.txt',sep=';',header=None , names=['text','emotion'])

In [52]:
# import string
# import nltk
# from nltk.corpus import stopwords

# # Reload DataFrame
# df = pd.read_csv('train.txt',sep=';',header=None , names=['text','emotion'])

# # Ensure stopwords are downloaded and defined
# try:
#     nltk.data.find('corpora/stopwords')
# except nltk.downloader.DownloadError:
#     nltk.download('stopwords')
# stop_words = set(stopwords.words('english'))

# # Define preprocessing functions locally for self-containment
# def remove_punc(text):
#   for punc in string.punctuation:
#     text = text.replace(punc,'')
#   return text

# def remove_numbers(txt):
#   new =""
#   for i in txt:
#     if not i.isdigit():
#       new += i
#   return new

# def remove_emojis(txt):
#   new =""
#   for i in txt:
#     if i.isascii():
#       new += i
#   return new

# def remove(txt):
#   words = txt.split()
#   new_words = []
#   for i in words:
#     if i not in stop_words:
#       new_words.append(i)
#   return ' '.join(new_words)

# # Apply all preprocessing steps in sequence
# df['text'] = df['text'].apply(lambda x : x.lower())
# df['text'] = df['text'].apply(remove_punc)
# df['text'] = df['text'].apply(remove_numbers)
# df['text'] = df['text'].apply(remove_emojis)
# df['text'] = df['text'].apply(remove)

# # Convert emotion to numbers
# unique_emotions = df['emotion'].unique()
# emotion_numbers = {}
# i = 0
# for emo in unique_emotions:
#   emotion_numbers[emo] = i
#   i += 1
# df['emotion'] = df['emotion'].map(emotion_numbers)

In [53]:
df.head()

                                                text  emotion
0                            i didnt feel humiliated  sadness
1  i can go from feeling so hopeless to so damned...  sadness
2   im grabbing a minute to post i feel greedy wrong    anger
3  i am ever feeling nostalgic about the fireplac...     love
4                               i am feeling grouchy    anger

In [54]:
df.isnull().sum()

text       0
emotion    0
dtype: int64

In [55]:
#unique emotion
unique_emotions = df['emotion'].unique()
emotion_numbers = {}
i = 0
for emo in unique_emotions:
  emotion_numbers[emo] = i
  i += 1

df['emotion'] = df['emotion'].map(emotion_numbers)

In [56]:
df

                                                    text  emotion
0                                i didnt feel humiliated        0
1      i can go from feeling so hopeless to so damned...        0
2       im grabbing a minute to post i feel greedy wrong        1
3      i am ever feeling nostalgic about the fireplac...        2
4                                   i am feeling grouchy        1
...                                                  ...      ...
15995  i just had a very brief time in the beanbag an...        0
15996  i am now turning and i feel pathetic that i am...        0
15997                     i feel strong and good overall        5
15998  i feel like this was such a rude comment and i...        1
15999  i know a lot but i feel so stupid because i ca...        0

[16000 rows x 2 columns]

In [57]:
df['text'] =df['text'].apply(lambda x : x.lower())

In [58]:
import string
def remove_punc(text):
  for punc in string.punctuation:
    text = text.replace(punc,'')
  return text

In [59]:
def remove_numbers(txt):
  new =""
  for i in txt:
    if not i.isdigit():
      new += i
  return new

df['text'] = df['text'].apply(remove_numbers)

In [60]:
def remove_emojis(txt):
  new =""
  for i in txt:
    if i.isascii(): # Corrected: Keep ASCII characters, thus removing non-ASCII (emojis)
      new += i
  return new

df['text'] = df['text'].apply(remove_emojis)

In [61]:
import nltk

In [62]:
from nltk.corpus import stopwords
from nltk.tokenize import word_tokenize

In [63]:
nltk.download('stopwords')
nltk.download('punkt')
nltk.download('punkt_tab')

[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!
[nltk_data] Downloading package punkt to /root/nltk_data...
[nltk_data]   Package punkt is already up-to-date!
[nltk_data] Downloading package punkt_tab to /root/nltk_data...
[nltk_data]   Package punkt_tab is already up-to-date!

True

In [64]:
stop_words = set(stopwords.words('english'))
len(stop_words)

198

In [65]:
stop_words

{'a',
 'about',
 'above',
 'after',
 'again',
 'against',
 'ain',
 'all',
 'am',
 'an',
 'and',
 'any',
 'are',
 'aren',
 "aren't",
 'as',
 'at',
 'be',
 'because',
 'been',
 'before',
 'being',
 'below',
 'between',
 'both',
 'but',
 'by',
 'can',
 'couldn',
 "couldn't",
 'd',
 'did',
 'didn',
 "didn't",
 'do',
 'does',
 'doesn',
 "doesn't",
 'doing',
 'don',
 "don't",
 'down',
 'during',
 'each',
 'few',
 'for',
 'from',
 'further',
 'had',
 'hadn',
 "hadn't",
 'has',
 'hasn',
 "hasn't",
 'have',
 'haven',
 "haven't",
 'having',
 'he',
 "he'd",
 "he'll",
 "he's",
 'her',
 'here',
 'hers',
 'herself',
 'him',
 'himself',
 'his',
 'how',
 'i',
 "i'd",
 "i'll",
 "i'm",
 "i've",
 'if',
 'in',
 'into',
 'is',
 'isn',
 "isn't",
 'it',
 "it'd",
 "it'll",
 "it's",
 'its',
 'itself',
 'just',
 'll',
 'm',
 'ma',
 'me',
 'mightn',
 "mightn't",
 'more',
 'most',
 'mustn',
 "mustn't",
 'my',
 'myself',
 'needn',
 "needn't",
 'no',
 'nor',
 'not',
 'now',
 'o',
 'of',
 'off',
 'on',
 'once',
 'only',
 'or',
 'other',
 'our',
 'ours',
 'ourselves',
 'out',
 'over',
 'own',
 're',
 's',
 'same',
 'shan',
 "shan't",
 'she',
 "she'd",
 "she'll",
 "she's",
 'should',
 "should've",
 'shouldn',
 "shouldn't",
 'so',
 'some',
 'such',
 't',
 'than',
 'that',
 "that'll",
 'the',
 'their',
 'theirs',
 'them',
 'themselves',
 'then',
 'there',
 'these',
 'they',
 "they'd",
 "they'll",
 "they're",
 "they've",
 'this',
 'those',
 'through',
 'to',
 'too',
 'under',
 'until',
 'up',
 've',
 'very',
 'was',
 'wasn',
 "wasn't",
 'we',
 "we'd",
 "we'll",
 "we're",
 "we've",
 'were',
 'weren',
 "weren't",
 'what',
 'when',
 'where',
 'which',
 'while',
 'who',
 'whom',
 'why',
 'will',
 'with',
 'won',
 "won't",
 'wouldn',
 "wouldn't",
 'y',
 'you',
 "you'd",
 "you'll",
 "you're",
 "you've",
 'your',
 'yours',
 'yourself',
 'yourselves'}

In [66]:
df.loc[1]['text']

'i can go from feeling so hopeless to so damned hopeful just from being around someone who cares and is awake'

In [67]:
def remove(txt):
  words = txt.split()
  new_words = []
  for i in words:
    if i not in stop_words:
      new_words.append(i)
  return ' '.join(new_words)

In [68]:
df['text'] = df['text'].apply(remove)

In [69]:
df.head()

                                                text  emotion
0                              didnt feel humiliated        0
1  go feeling hopeless damned hopeful around some...        0
2          im grabbing minute post feel greedy wrong        1
3  ever feeling nostalgic fireplace know still pr...        2
4                                    feeling grouchy        1

In [70]:
from sklearn.model_selection import train_test_split

# Filter out rows where 'text' is an empty string after preprocessing
df_filtered = df[df['text'].str.strip() != '']

X = df_filtered['text']
y = df_filtered['emotion']

X_train, X_test, y_train, y_test = train_test_split( X, y, test_size=0.33, random_state=42)

In [71]:
X_test

8756                             ive made week feel beaten
4660                              feel strategy worthwhile
6095                     feel worthless weak say want find
304                                        feel clever nov
8241                      im moved ive feeling kind gloomy
                               ...
12538    feel really ought assert way smiles pleasant b...
6536     even sure formulate thoughts since put feeling...
13806         really feel quite honoured represent country
7724     ive feeling little overwhelmed whole thing lat...
5121     wanting write secret life live one handful peo...
Name: text, Length: 5280, dtype: object

In [72]:
df.shape

(16000, 2)

In [73]:
from sklearn.feature_extraction.text import TfidfTransformer ,CountVectorizer

In [74]:
bow_vectorizer = CountVectorizer()

In [75]:
X_train_bow = bow_vectorizer.fit_transform(X_train)
X_test_bow = bow_vectorizer.transform(X_test) # Corrected: Use transform for the test set

In [76]:
from sklearn.naive_bayes import MultinomialNB
from sklearn.metrics import accuracy_score

In [77]:
nb_model = MultinomialNB()
nb_model.fit(X_train_bow, y_train)

MultinomialNB()

In [78]:
pred_nb = nb_model.predict(X_test_bow)
print(accuracy_score(y_test, pred_nb))

0.7647727272727273

In [79]:
y_test

8756     0
4660     5
6095     0
304      5
8241     0
        ..
12538    5
6536     4
13806    5
7724     4
5121     0
Name: emotion, Length: 5280, dtype: int64

In [80]:
tfidf_vectorizer = TfidfTransformer()
X_train_tfidf = tfidf_vectorizer.fit_transform(X_train_bow)
X_test_tfidf = tfidf_vectorizer.transform(X_test_bow)

nb_model_tfidf = MultinomialNB()
nb_model_tfidf.fit(X_train_tfidf, y_train)
pred_nb_tfidf = nb_model_tfidf.predict(X_test_tfidf)

In [81]:
print(accuracy_score(y_test, pred_nb_tfidf))

0.6606060606060606

In [82]:
from sklearn.linear_model import LogisticRegression
logistic_model = LogisticRegression(max_iter=1000)
logistic_model.fit(X_train_tfidf, y_train)
pred_logistic = logistic_model.predict(X_test_tfidf)

In [83]:
print(accuracy_score(y_test, pred_logistic))

0.8479166666666667